### ISSUE TITLE
Suggestion to rename /icons directory for simpler compatibility with Apache web server

### ISSUE THREAD

**Issue by pyvain** [jakewies/hugo-theme-codex#47]
Most Apache web server installations come out of the box with a configuration file treating the `/icons/` route as a special case.

More precisely, the `mod_alias` configuration file (enabled by default) sets the `/icons/` route to point to the `/usr/share/apache2/icons/` folder on the server instead of the `/icons` folder of the website being served.

Here is a mention of the "problem": https://serverfault.com/questions/153177/apache2-and-icons-path-behaving-differently

Using this route to serve images for the template may cause unexpected problems for Apache users unaware of this default configuration, such as 404 errors for images contained in the `/icons` folder.

I suggest renaming the folder/route to something like `/images` or `/social` to embrace a larger public :slightly_smiling_face: .

**Comment by kentnek** [comment]
Yeah I don't mind putting the images to '/images` and social icons to `/images/social`. Whaddya think @jakewies?

**Comment by jakewies** [comment]
Thinking out loud here:

Hugo takes anything in the `static/` directory and puts it at the website root for use in the app. So the `static/icons/` directory can be accessed at `www.your-site.com/icons/`. This is a problem for Apache users because their server treats the `/icons` route as a special case.

Do I have that right?

And the proposed change is to replace the `static/icons/` directory with a `static/images/` directory? And inside that we can put icons at `static/images/social/<icon_name>.svg`?

**Comment by kentnek** [comment]
> Do I have that right?

Yes it appears to be [the case](https://electrictoolbox.com/apache-icons-directory/). In our HTML code we do often refer to the path `/icons/...`, which Apache2 servers will treat as `usr/share/apache2/icons/...`. 

Also `/images` is a more commonly used paths for static image resources so I'm fine with changing that.

**Comment by jakewies** [comment]
Ok I'm totes on board with this.

**Comment by pyvain** [comment]
Here is a PR :slightly_smiling_face:

**Comment by pyvain** [comment]
Merged :slightly_smiling_face:
