### ISSUE TITLE
[IMPORTANT] Demo site is broken

### ISSUE THREAD

**Issue by kentnek** [jakewies/hugo-theme-codex#61]
![image](https://user-images.githubusercontent.com/7024160/86252257-8d416700-bbe5-11ea-9d0b-8d7b7f3b397d.png)

@jakewies could you look into this?

**Comment by kentnek** [comment]
I think the build process for that is somehow broken
![image](https://user-images.githubusercontent.com/7024160/86252404-c2e65000-bbe5-11ea-867e-f42285772a38.png)

**Comment by jakewies** [comment]
This is a strange issue. The master branch builds just fine, but the hosted demo on themes.gohugo.io break. The hosted demo is also trying to request `scss` files instead of the `static/css` files.

**Comment by kentnek** [comment]
@jakewies is the hosted demo using `hugo-extended`? also i think you linked the wrong issue in your comment

**Comment by jakewies** [comment]
It could be that. I mentioned it in the issue. I also updated the issue link.

**Comment by kentnek** [comment]
Oh I didn't know there was a repo for all the themes. It turns out:
```
Each theme needs:
5. To include the resources folder if it's using Hugo Pipes to process assets;
```

Looks like we need to include the `/resources/_gen` folder for the demo site to work. I've also looked at [a theme](https://github.com/kimcc/hugo-theme-noteworthy/tree/de668f23496e2658924ea749d87e7acbd6fad405) that I used previously and they did that as well.

**Comment by kentnek** [comment]
@jakewies can you update the commit reference in the themes repo too? I don't know how to do that

**Comment by jakewies** [comment]
@kentnek Not sure how to do that either. If you're referring to the fact that the theme demo is still broken even after https://github.com/jakewies/hugo-theme-codex/pull/62, it might be because of [this](https://github.com/gohugoio/hugoThemes#theme-updates). Looks like the themes get updated at:

```
00:00 UTC on the 1, 4, 7, 10, 13, 16, 19, 22, 25, 28 and 31th of every month
```

The readme for the hugo themes repo doesn't have any docs on how to update a commit reference. I will go ahead and create a new release in GitHub for this theme in the meantime, and we'll keep an eye on the demo in the coming days.
