### ISSUE TITLE
Emoji styling

### ISSUE THREAD

**Issue by dbrennand** [jakewies/hugo-theme-codex#94]
Hi,

I am looking to use this Hugo theme. However, in different browsers, I am experiencing some inconsistencies with the emoji styling.

In chrome emojis look similar to:
![image](https://user-images.githubusercontent.com/52419383/87982572-86ac5e00-cac6-11ea-85c3-4ab5215b3551.png)
![image](https://user-images.githubusercontent.com/52419383/87982656-a6dc1d00-cac6-11ea-88fd-c87d835e60c4.png)
Whereas in Firefox:
![image](https://user-images.githubusercontent.com/52419383/87982732-c1ae9180-cac6-11ea-9d42-dbe557883eeb.png)
![image](https://user-images.githubusercontent.com/52419383/87982771-d1c67100-cac6-11ea-9031-334bbcdb561d.png)

Furthermore, on another page, the emoji's on Firefox seem to resemble the format similar to how they are displayed in chrome:
![image](https://user-images.githubusercontent.com/52419383/87982861-fb7f9800-cac6-11ea-9110-84976b83f58f.png)

There seems to be some inconsistencies here. Is there any way I can make them always look how they are presented in Firefox?

Thanks :smile:

**Comment by dbrennand** [comment]
It is also worth noting that I have added the following to the config.toml file:
```toml
enableEmoji = true
```
From the following [documentation](https://gohugo.io/getting-started/configuration/):
![image](https://user-images.githubusercontent.com/52419383/87983588-21f20300-cac8-11ea-8d5b-f40f7fec03de.png)

**Comment by dgnicholson** [comment]
Hi @dbrennand . I can't seem to reproduce the issue as the wave emoji appears the same on both Firefox and Chrome for me on Windows. 
![image](https://user-images.githubusercontent.com/6208288/88071419-2b23b400-cb4a-11ea-911f-7c28c972eaaa.png)

There's some slight variation on Linux and iOS as would be expected, but nothing like you identify. 

Have you made any other changes to the theme?

**Comment by dbrennand** [comment]
Hi @dgnicholson 
Do you have `enableEmoji = true` set in your `config.toml` file?

I am using Firefox and Chrome on Linux. That might be why?

**Comment by dgnicholson** [comment]
I did update my config.toml and tested with it enabled and not. 

I do suspect it's your Linux distro. What are you running? I tested on Ubuntu which uses [Google’s Noto Color emoji font](https://www.google.com/get/noto/help/emoji/) right out of the box I believe.

**Comment by dbrennand** [comment]
> I did update my config.toml and tested with it enabled and not.
> 
> I do suspect it's your Linux distro. What are you running? I tested on Ubuntu which uses [Google’s Noto Color emoji font](https://www.google.com/get/noto/help/emoji/) right out of the box I believe.

I am running Fedora 32 :smile:

**Comment by dgnicholson** [comment]
@dbrennand Yeah, that's probably the issue. Try installing the Google Noto emoji font and see if that resolves the problem. If you search in the package manager there should be a color and no color version.  

Firefox ships with the Twemoji Mozilla font which is why you're seeing some colored emoji in FF, but it's buggy. There is an issue affecting many distros where if sans-serif fonts are used some emojis appear black and white. I was actually able to reproduce this on Ubuntu 18.04 as well. I resolved it by digging into the FF about:config and removing the value (`sans-serif`) from `font.name-list.sans-serif.x-western` but YMMV. If you end up installing Google Noto you can have FF use it instead by updating the `font.name-list.emoji` config to `Noto Color Emoji`.

**Comment by dbrennand** [comment]
Hi @dgnicholson 

Thanks for the reply! I will try this tonight and report back 😄 👍

**Comment by dbrennand** [comment]
Hey @dgnicholson 
In Firefox I removed the value `sans-serif` from `font.name-list.sans-serif.x-western` and emojis are showing correctly now! Thanks a lot for your help! :smile:
